### ISSUE TITLE
Any official docker image released?

### ISSUE THREAD

**Issue by changchiyou** [Palats/mapshot#53]
I saw this

https://github.com/Palats/mapshot/blob/7ec20a62ae74c687c2a5ae699fd029b661258619/README.md?plain=1#L96

but I can't find any guide for docker user, have I missed something? (https://github.com/Palats/mapshot/discussions/26 seems like a uncomplete task)

**Comment by Palats** [comment]
No, as the README state, that is relatively advanced setup, so you're mostly on your own on that one. I also have no desire to maintain an official image for the time being. Also, note that distributing a docker image would not be allowed to contain Factorio itself, so that would be of limited interest I think.

That being said, if someone is willing to contribute a clean Dockerfile, that might be an option (not sure - it depends what it looks like I guess).

**Comment by changchiyou** [comment]
It might be a good idea to check the latest version & download regularly with https://wiki.factorio.com/Download_API, instead of containing Factorio itself inside the docker image.

**Comment by martydingo** [comment]
I did create one for myself

https://github.com/martydingo/factorio-mapshot-docker

&

https://hub.docker.com/r/martydingo/mapshot

I run it with Kubernetes, however usage should be similar.

**Comment by martydingo** [comment]
I run it with two containers in a single deployment, you can achieve this with docker-compose also.

```yaml
        - image: martydingo/mapshot:latest
          imagePullPolicy: Always
          name: mapshot-renderer
          env:
            - name: FACTORIO_USERNAME
              value: "martydingo"
            - name: FACTORIO_TOKEN
              value: "8ce1d199f81a7197779db938ffc51b"
            - name: FACTORIO_SAVE
              value: "/opt/factorio/saves/rail-age.factorio.dingo.nexus.zip"
            - name: MAPSHOT_AREA
              value: "_all_"
            # - name: MAPSHOT_FACTORIO_BINARY_PATH
            #   value: "/mapshot/factorio/bin/x64/factorio"
            # - name: MAPSHOT_FACTORIO_DATA_DIRECTORY
            #   value: "/mapshot/factorio"
            - name: MAPSHOT_JPEG_QUALITY
              value: "95"
            - name: MAPSHOT_MINIMUM_JPEG_QUALITY
              value: "95"
            # - name: MAPSHOT_MAXIMUM_TILES
            #   value: ""
            - name: MAPSHOT_MINIMUM_TILES
              value: "64"
            - name: MAPSHOT_MODE
              value: "render"
            # - name: MAPSHOT_ROOT_DIRECTORY
            #   value: "/mapshot"
            - name: MAPSHOT_SURFACES_TO_RENDER
              value: "_all_"
            # - name: MAPSHOT_VERBOSE_FACTORIO_LOGGING
            #   value: ""
            - name: MAPSHOT_VERBOSE_MAPSHOT_LOG_LEVEL_INT
              value: "9"
            # - name: MAPSHOT_WORKING_DIRECTORY
            #   value: "/mapshot/factorio"
            - name: MAPSHOT_INTERVAL
              value: "600"
          volumeMounts:
            - mountPath: /opt/factorio
              name: factorio-mapshot-rail-age-factorio-dingo-nexus
              readOnly: true
            - mountPath: /mapshot
              name: mapshot-mapshot-rail-age-factorio-dingo-nexus
        - image: martydingo/mapshot:latest
          imagePullPolicy: Always
          name: mapshot-server
          env:
            # - name: MAPSHOT_FACTORIO_BINARY_PATH
            #   value: "/mapshot/factorio/bin/x64/factorio"
            # - name: MAPSHOT_FACTORIO_DATA_DIRECTORY
            #   value: "/mapshot/factorio"
            - name: MAPSHOT_MODE
              value: "serve"
            # - name: MAPSHOT_ROOT_DIRECTORY
            #   value: "/mapshot"
            - name: MAPSHOT_VERBOSE_MAPSHOT_LOG_LEVEL_INT
              value: "9"
            # - name: MAPSHOT_WORKING_DIRECTORY
            #   value: "/mapshot/factorio"
```

**Comment by martydingo** [comment]
I run it with two containers in a single deployment, you can achieve this with docker-compose also.

```yaml
        - image: martydingo/mapshot:latest
          imagePullPolicy: Always
          name: mapshot-renderer
          env:
            - name: FACTORIO_USERNAME
              value: "username"
            - name: FACTORIO_TOKEN
              value: "token"
            - name: FACTORIO_SAVE
              value: "/opt/factorio/saves/rail-age.factorio.dingo.nexus.zip"
            - name: MAPSHOT_AREA
              value: "_all_"
            # - name: MAPSHOT_FACTORIO_BINARY_PATH
            #   value: "/mapshot/factorio/bin/x64/factorio"
            # - name: MAPSHOT_FACTORIO_DATA_DIRECTORY
            #   value: "/mapshot/factorio"
            - name: MAPSHOT_JPEG_QUALITY
              value: "95"
            - name: MAPSHOT_MINIMUM_JPEG_QUALITY
              value: "95"
            # - name: MAPSHOT_MAXIMUM_TILES
            #   value: ""
            - name: MAPSHOT_MINIMUM_TILES
              value: "64"
            - name: MAPSHOT_MODE
              value: "render"
            # - name: MAPSHOT_ROOT_DIRECTORY
            #   value: "/mapshot"
            - name: MAPSHOT_SURFACES_TO_RENDER
              value: "_all_"
            # - name: MAPSHOT_VERBOSE_FACTORIO_LOGGING
            #   value: ""
            - name: MAPSHOT_VERBOSE_MAPSHOT_LOG_LEVEL_INT
              value: "9"
            # - name: MAPSHOT_WORKING_DIRECTORY
            #   value: "/mapshot/factorio"
            - name: MAPSHOT_INTERVAL
              value: "600"
          volumeMounts:
            - mountPath: /opt/factorio
              name: factorio-mapshot-rail-age-factorio-dingo-nexus
              readOnly: true
            - mountPath: /mapshot
              name: mapshot-mapshot-rail-age-factorio-dingo-nexus
        - image: martydingo/mapshot:latest
          imagePullPolicy: Always
          name: mapshot-server
          env:
            # - name: MAPSHOT_FACTORIO_BINARY_PATH
            #   value: "/mapshot/factorio/bin/x64/factorio"
            # - name: MAPSHOT_FACTORIO_DATA_DIRECTORY
            #   value: "/mapshot/factorio"
            - name: MAPSHOT_MODE
              value: "serve"
            # - name: MAPSHOT_ROOT_DIRECTORY
            #   value: "/mapshot"
            - name: MAPSHOT_VERBOSE_MAPSHOT_LOG_LEVEL_INT
              value: "9"
            # - name: MAPSHOT_WORKING_DIRECTORY
            #   value: "/mapshot/factorio"
```
